routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\User;
use App\Permisos\Models\Role;
use App\Permisos\Models\Permission;
use Illuminate\Support\Facades\Gate;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::resource('/role', 'RoleController')->names('role');
Route::resource('/reportes', 'ReportesController')->names('reportes');
Route::get('/reportes/seleccion/{formulario}', 'ReportesController@formulario');
Route::post('/reportes/generate', 'ReportesController@generate')->name('reportes.generate');

Route::resource('/user', 'UserController', ['except' => [
        'create', 'store']])->names('user');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use App\Permisos\Traits\UserTrait;

class User extends Authenticatable
{
    use Notifiable, UserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    

   
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Permisos\Models\Role;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize('haveaccess','user.index');
        $users =  User::with('roles')->orderBy('id','Desc')->paginate(2);
        //return $users; 

        return view('user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //$this->authorize('create', User::class);
        //return 'Create';
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $this->authorize('view', [$user, ['user.show','userown.show'] ]);
        $roles= Role::orderBy('name')->get();

        //return $roles;

        return view('user.view', compact('roles', 'user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $this->authorize('update', [$user, ['user.edit','userown.edit'] ]);
        $roles= Role::orderBy('name')->get();

        //return $roles;

        return view('user.edit', compact('roles', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name'          => 'required|max:50|unique:users,name,'.$user->id,
            'email'         => 'required|max:50|unique:users,email,'.$user->id            
        ]);

        //dd($request->all());

        $user->update($request->all());

        $user->roles()->sync($request->get('roles'));
        
        return redirect()->route('user.index')
            ->with('status_success','Actualización exitosa!'); 



    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $this->authorize('haveaccess','user.destroy');
        $user->delete();

        return redirect()->route('user.index')
            ->with('status_success','Usuario eliminado'); 
    }
}

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h2>Edición de Usuario</h2></div>

                <div class="card-body">
                    @include('custom.message')
                    <form action="{{ route('user.update', $user->id)}}" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="container">
                            <div class="form-group">                            
                                <input type="text" class="form-control" 
                                       id="name" 
                                       placeholder="Name"
                                       name="name"
                                       value="{{ old('name', $user->name)}}"
                                       >
                            </div>
                            <div class="form-group">                            
                                <input type="text" 
                                       class="form-control" 
                                       id="email" 
                                       placeholder="email"
                                       name="email"
                                       value="{{ old('email' , $user->email)}}"
                                       >
                            </div>

                            <div class="form-group">                            
                                <select  class="form-control"  name="roles" id="roles">
                                    @foreach($roles as $role)
                                    <option value="{{ $role->id }}"
                                            @isset($user->roles[0]->name)
                                            @if($role->name ==  $user->roles[0]->name)
                                            selected
                                            @endif
                                            @endisset


                                            >{{ $role->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <hr>
                            <input class="btn btn-primary" type="submit" value="Actualizar">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h2>Usuarios del sistema</h2></div>

                <div class="card-body">

                    @include('custom.message')

                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Correo</th>
                                <th scope="col">Rol(es)</th>
                                <th colspan="3"></th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($users as $user)

                            <tr>
                                <th scope="row">{{ $user->id}}</th>
                                <td>{{ $user->name}}</td>
                                <td>{{ $user->email}}</td>
                                <td>
                                    @isset( $user->roles[0]->name )
                                    {{ $user->roles[0]->name}}
                                    @endisset

                                </td>
                                <td> 
                                    @can('view',[$user, ['user.show','userown.show'] ])
                                    <a class="btn btn-info" href="{{ route('user.show',$user->id)}}">Ver</a> 
                                    @endcan
                                </td>  
                                <td> 
                                    @can('view', [$user, ['user.edit','userown.edit'] ])
                                    <a class="btn btn-success" href="{{ route('user.edit',$user->id)}}">Editar</a> 
                                    @endcan
                                </td>  
                                <td> 
                                    @can('haveaccess','user.destroy')
                                    <form action="{{ route('user.destroy',$user->id)}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger">Eliminar</button>
                                    </form>
                                    @endcan


                                </td>  
                            </tr>      
                            @endforeach
                        </tbody>
                    </table>

                    {{ $users->links() }}

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header"><h2>Detalle del usuario</h2></div>

                <div class="card-body">
                    @include('custom.message')
                    <form action="{{ route('user.update', $user->id)}}" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="container">
                            <div class="form-group">                            
                                <input type="text" class="form-control" 
                                       id="name" 
                                       placeholder="Name"
                                       name="name"
                                       value="{{ old('name', $user->name)}}"
                                       disabled>
                            </div>
                            <div class="form-group">                            
                                <input type="text" 
                                       class="form-control" 
                                       id="email" 
                                       placeholder="email"
                                       name="email"
                                       value="{{ old('email' , $user->email)}}"
                                       disabled>
                            </div>

                            <div class="form-group">                            
                                <select disabled class="form-control"  name="roles" id="roles">
                                    @foreach($roles as $role)
                                    <option value="{{ $role->id }}"
                                            @isset($user->roles[0]->name)
                                            @if($role->name ==  $user->roles[0]->name)
                                            selected
                                            @endif
                                            @endisset


                                            >{{ $role->name }}</option>
                                    @endforeach
                                </select>
                            </div>


                            <hr>

                            <a class="btn btn-success" href="{{route('user.edit',$user->id)}}">Editar</a>
                            <a class="btn btn-danger" href="{{route('user.index')}}">Regresar</a>

                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection